name: Auto Update 
on: 
  workflow_dispatch:
  push: 
    branches: 
      - otherbranch 

jobs: 
  update: 
    runs-on: ubuntu-latest 
    steps: 
      - uses: actions/checkout@v3 
      - uses: tj-actions/changed-files@v38 
        id: changed-files 
      - name: List all changed files 
        run: | 
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do 
            echo "$file was changed" 
          done 
      - name: Update main branch 
        run: | 
          git checkout main 
          git merge otherbranch 
          git push
