name: Pipeline

on:  
  push:
     paths:
      - otherbranch
      
  pull_request:
    branches:
      - main 
      - otherbranch
  workflow_dispatch:

jobs:  
  CICD:    
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2         
        with:
          fetch-depth: 2
        
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7' 
          
      - name: Install dependencies
        run:  python -m pip install --upgrade pip
          
      - name: 1Find Difference between branch and commit
        id: Finddiff        
        run:  echo "::set-output name=fileswithdepth::$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | xargs)"          
        #run:  echo "::set-output name=fileswithdepth::$(git diff --name-only origin/main origin/${GITHUB_HEAD_REF} | xargs)"          
        shell: bash
        
      - name: 2get changed files
        id: getfile
        run: |
          echo "::set-output name=files::$(git diff-tree --no-commit-id --name-only -r ${{ github.sha }} | xargs)"
      - name: 2echo output
        run: |
          echo ${{ steps.getfile.outputs.files }} 
       

     
      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: naveenkarthikv/newrepository
      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

