name: Get-All-Dags-Tested
# on:  [push]   
on:  
  push:
     paths:
      - 'dags/**'
      - 'utils/**'
      - 'sql/**'
  pull_request:
    branches:
      - main      
  workflow_dispatch:

jobs:  
  Get-All-Dags-Tested:    
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2         
        with:
          fetch-depth: 2   # 0 will get entire history  
        
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7' 
          
      - name: Install dependencies
        run:  python -m pip install --upgrade pip
          
      - name: 1Find Difference between branch and commit
        id: Finddiff        
        run:  echo "::set-output name=fileswithdepth::$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | xargs)"          
        #run:  echo "::set-output name=fileswithdepth::$(git diff --name-only origin/main origin/${GITHUB_HEAD_REF} | xargs)"          
        shell: bash
      - name: 2get changed files
        id: getfile
        run: |
          echo "::set-output name=files::$(git diff-tree --no-commit-id --name-only -r ${{ github.sha }} | xargs)"
      - name: 2echo output
        run: |
          echo ${{ steps.getfile.outputs.files }} 
       

      - name: Move the files to temp directory
        id: Movefiles    
        run: |        
          echo ${{ steps.Finddiff.outputs.fileswithdepth }}          
          mkdir -p temp_dags/{utils,plugins,sql}
          echo "Files with depth"
          for changed_file in ${{ steps.Finddiff.outputs.fileswithdepth }}; do
            file_path=$(dirname "${changed_file}")
            file_name=$(basename "${changed_file}")
            if [ "${file_path}" = "dags" ]; then
                echo "in if loop:${file_path}."  
                echo "in if loop:${file_name}."   
              cp ${changed_file} temp_dags/  
            else   
              echo "OUT if loop:${file_path}."  
              echo "OUT if loop:${file_name}."  
              mkdir -p temp_dags/${file_path}  
              cp ${changed_file} temp_dags/${file_path}  
            fi
          done
          #cp utils/* temp_dags/utils/
          #cp plugins/* temp_dags/plugins/
          ls -R temp_dags/
        
      - name: Set AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
          aws_bucket: ${{ secrets.AWS_BUCKET }}
          source_dir: temp_dags
          destination_dir: github
      - name: Deploy to S3
        run: |
          pip install boto3
          # python upolad_dags_to_s3.py
