name: Compare and Commit

on:
  workflow_dispatch:
  push:
    branches:
      - main
permissions:
 id-token: write
 contents: write
 actions: write
 checks: write
 deployments: write
 discussions: write
 issues: write
 pages: read
 packages: write
 pull-requests: write
 repository-projects: write
 security-events: write
 statuses: write

jobs:
  checkout:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout main branch
      uses: actions/checkout@v2

    - name: git setup
      run: |
        git config --global user.email "naveenkarthik5764@gmail.com"
        git config --global user.name "NaveenKarthikV"
        git clone https://github.com/NaveenKarthikV/gitactions-cicd.git
        cd gitactions-cicd 

  compare_branch:
    needs: [checkout]
    runs-on: ubuntu-latest
    steps:
      - name: Create Pull Request
        uses: NaveenKarthikV/create-pull-request@v5
        with:
         branch: other-branch


  merging:
          needs: [compare_branch]
          runs-on: ubuntu-latest
          steps:
            - id: automerge
              name: merge Pull Request
              uses: "NaveenKarthikV/automerge-action@v0.15.6"  
