name: Compare the branches

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - otherbranch

jobs:
  Compare_the_branches:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Compare and Move Files
        id: compare-and-move
        run: |
          # Define the destination directory
          destination_dir="temp_dags"

          # Create the destination directory
          mkdir -p "$destination_dir"

          # Find and copy files with depth preserving structure
          git diff --name-only "${{ github.event.before }}" "${{ github.sha }}" |
          while IFS= read -r changed_file; do
            if [[ "$changed_file" == *"/dags/"* ]]; then
              echo "in if loop: $changed_file"
              cp "$changed_file" "$destination_dir/"
            else
              echo "OUT if loop: $changed_file"
              mkdir -p "$destination_dir/$(dirname "$changed_file")"
              cp "$changed_file" "$destination_dir/$changed_file"
            fi
          done

      - name: List Moved Files
        run: ls -R "$destination_dir/"

      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: naveenkarthikv/newrepository
      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}


        
