name: Update mainbranch on changes to otherbranch
on:
  workflow_dispatch:
  push:
    branches:
      - otherbranch

jobs:
  update-mainbranch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout mainbranch
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Pull changes from otherbranch
        run: git config --global pull origin/otherbranch   

      - name: Merge changes into mainbranch
        run: git merge otherbranch

      - name: Push changes to mainbranch
        run: git push origin main
