name: Sync Feature Branch to Main

on:
  push:
    branches:
      - feature

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Merge changes into main
        run: |
          git checkout main
          git merge origin/feature --no-commit --no-ff
          # Handle any conflicts and perform necessary testing here
          git commit -m "Merge changes from feature branch"
          git push origin main

