name: Compare and Commit

on:
  workflow_dispatch:
  push:
    branches:
      - main
permissions:
 id-token: write
 contents: write
 actions: write
 checks: write
 deployments: write
 discussions: write
 issues: write
 pages: read
 packages: write
 pull-requests: write
 repository-projects: write
 security-events: write
 statuses: write

jobs:
  checkout:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout main branch
      uses: actions/checkout@v2

    - name: git setup
      run: |
        git config --global user.email "naveenkarthik5764@gmail.com"
        git config --global user.name "NaveenKarthikV"
        git clone https://github.com/NaveenKarthikV/gitactions-cicd.git
        sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-key C99B11DEB97541F0
        sudo apt-add-repository https://cli.github.com/packages
        sudo apt update
        sudo apt install gh
        gh auth login
        cd gitactions-cicd 

  compare_branch:
     needs: [checkout]
     runs-on: ubuntu-latest
     steps:
       - name: Create Pull Request
         uses: NaveenKarthikV/create-pull-request@v5
         with:
          branch: other-branch


  merging:
          needs: [checkout]
          runs-on: ubuntu-latest
          steps:
            - id: automerge
              name: merge Pull Request
              run: |
               gh pr create --base base-branch --head other-branch  --title "test" --body "test"
