name: Compare the branches
on:
  push: 
    branches:
      - main
      - otherbranch
    paths:
      - 'newsql/**'
      - 'python/**'
      - 'sql/**'
  pull_request:
    branches:
      - otherbranch  
    paths:
    - 'newsql/**'
    - 'python/**'
    - 'sql/**' 

  workflow_dispatch:

jobs:  
   Compare_the_branches:    
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3         
        with:
          fetch-depth: 0    

      - name: check the Difference
        id: Finddiff        
        run:  echo "::set-output name=fileswithdepth::$(git diff --name-status ${{ github.event.before }} ${{ github.sha }} | xargs)"           
        shell: bash
        
      - name: Changed files
        id: getfile
        run: |
          echo "::set-output name=files::$(git diff-tree --no-commit-id --name-only -r ${{ github.sha }} | xargs)"
      - name: echo output
        run: |
          echo ${{ steps.getfile.outputs.files }} 

      - name: Move the files to temp directory
        id: Movefiles    
        run: |        
          echo ${{ steps.Finddiff.outputs.fileswithdepth }}          
          mkdir -p temp_dags/{newsql,python,sql}
          for changed_file in ${{ steps.Finddiff.outputs.fileswithdepth }}; do
            file_path=$(dirname "${changed_file}")
            file_name=$(basename "${changed_file}")
            if [ "${file_path}" = "dags" ]; then
                echo "in if loop:${file_path}."  
                echo "in if loop:${file_name}."   
              cp ${changed_file} temp_dags/  
            else   
              echo "OUT if loop:${file_path}."  
              echo "OUT if loop:${file_name}."  
              mkdir -p temp_dags/${file_path}  
              cp ${changed_file} temp_dags/${file_path}  
            fi
          done
          ls -R temp_dags/
      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: naveenkarthikv/newrepository
      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
