name: Auto Update Workflow

on:
  workflow_dispatch:
  push:
    branches:
      - otherbranch
jobs:
  auto-update:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Update files
      run: |
        # Replace with the actual commands you need to update files/folders
        git config user.name "NaveenKarthikV"
        git config  user.name "naveenkarthik5764@gmail.com"
        git checkout otherbranch
        git merge otherbranch --no-commit --no-ff
        # Perform any necessary file/folder changes
        git commit -m "Auto-update files from otherbranch"
        git push
