name: Auto Update Workflow

on:
  workflow_dispatch:
  push:
    branches:
      - otherbranch


jobs:
  auto-update:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Fetch latest changes
      run: git fetch origin main:otherbranch

    - name: Check for changes
      id: check_changes
      run: |
        CHANGES=$(git log --pretty=oneline --abbrev-commit otherbranch..origin/main)
        echo "::set-output name=changes::$CHANGES"

    - name: Update files
      if: steps.check_changes.outputs.changes != ''
      run: |
        git config user.name NaveenkarthikV
        git config user.email naveenkarthik5764@gmail.com
        git checkout main
        git merge otherbranch --no-commit --no-ff
        # Perform any necessary file/folder changes
        git commit -m "Auto-update files from otherbranch"
        git push


